name: cfnat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Prepare binary files
      run: |
        if [ "${{ matrix.platform }}" = "linux/amd64" ]; then
          cp cfnat-linux-amd64 cfnat
          cp colo-linux-amd64 colo
        else
          cp cfnat-linux-arm64 cfnat
          cp colo-linux-arm64 colo
        fi
        chmod +x cfnat colo

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: ${{ matrix.platform }}
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/cffffff:latest-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          ${{ secrets.DOCKER_USERNAME }}/cffffff:${{ github.sha }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}

    - name: Create and push manifest
      if: ${{ matrix.platform == 'linux/amd64' }}
      run: |
        docker manifest create ${{ secrets.DOCKER_USERNAME }}/cffffff:latest \
          ${{ secrets.DOCKER_USERNAME }}/cffffff:latest-amd64 \
          ${{ secrets.DOCKER_USERNAME }}/cffffff:latest-arm64
        docker manifest push ${{ secrets.DOCKER_USERNAME }}/cffffff:latest
        
        docker manifest create ${{ secrets.DOCKER_USERNAME }}/cffffff:${{ github.sha }} \
          ${{ secrets.DOCKER_USERNAME }}/cffffff:${{ github.sha }}-amd64 \
          ${{ secrets.DOCKER_USERNAME }}/cffffff:${{ github.sha }}-arm64
        docker manifest push ${{ secrets.DOCKER_USERNAME }}/cffffff:${{ github.sha }}
