name: zt

on:
  repository_dispatch:
  workflow_dispatch:
    
env:
  test: 1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: |
           rm -rf dockerfile
           rm -rf config.ymal
           rm -rf entrypoint.sh
           git clone https://github.com/key-networks/ztncui-aio
           mv ztncui-aio/* .
         
           sed -i 's/github.com\/key-networks\/ztncui/gitee.com\/opopop880\/ztncui/g' .Dockerfile
           echo "TAG=1.2.11" >> $GITHUB_ENV
           
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      


    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ztncui:latest
            ${{ secrets.DOCKER_USERNAME }}/ztncui:${{ env.TAG }}
