name: Build tg-signer

on:
  push:
    branches: [ tg-signer ]  # 只监听tg-signer分支
  pull_request:
    branches: [ tg-signer ]
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: tg-signer  # 明确指定检出tg-signer分支的代码
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: CN.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/tg-signer:latest
          ${{ secrets.DOCKER_USERNAME }}/tg-signer:${{ github.sha }} 
